// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGoodsInfo = "goods_info"

// GoodsInfo 商品信息
type GoodsInfo struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                        // 主键ID
	GoodsType    int32     `gorm:"column:goods_type;not null;comment:商品分类" json:"goods_type"`                             // 商品分类
	GoodsName    string    `gorm:"column:goods_name;not null;comment:商品名称" json:"goods_name"`                             // 商品名称
	Price        int32     `gorm:"column:price;not null;comment:单价/分" json:"price"`                                       // 单价/分
	CoverImage   *string   `gorm:"column:cover_image;comment:封面图片" json:"cover_image"`                                    // 封面图片
	Sort         int32     `gorm:"column:sort;not null;comment:排序" json:"sort"`                                           // 排序
	PublishState int32     `gorm:"column:publish_state;not null;comment:上下架状态" json:"publish_state"`                      // 上下架状态
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	Deleted      int32     `gorm:"column:deleted;not null;comment:是否删除" json:"deleted"`                                   // 是否删除
}

// TableName GoodsInfo's table name
func (*GoodsInfo) TableName() string {
	return TableNameGoodsInfo
}
