// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCoin = "coin"

// Coin 币币信息
type Coin struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                       // 主键ID
	Name       string    `gorm:"column:name;not null;comment:币种" json:"name"`                                          // 币种
	InstID     string    `gorm:"column:inst_id;not null;comment:币种" json:"instId"`                                     // 币种
	CoinType   int32     `gorm:"column:coin_type;not null;comment:类型: 0 币 1 合约" json:"coinType"`                       // 类型: 0 币 1 合约
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	Deleted    bool      `gorm:"column:deleted;not null;comment:是否删除" json:"deleted"`                                  // 是否删除
}

// TableName Coin's table name
func (*Coin) TableName() string {
	return TableNameCoin
}
