// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderGoods = "order_goods"

// OrderGood 订单商品
type OrderGoods struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                       // 主键ID
	OrderID    int64     `gorm:"column:order_id;not null;comment:订单ID" json:"orderId"`                                 // 订单ID
	GoodsID    int64     `gorm:"column:goods_id;not null;comment:商品ID" json:"goodsId"`                                 // 商品ID
	Price      int32     `gorm:"column:price;not null;comment:商品单价" json:"price"`                                      // 商品单价
	Amount     int32     `gorm:"column:amount;not null;comment:商品数量" json:"amount"`                                    // 商品数量
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	Deleted    int32     `gorm:"column:deleted;not null;comment:是否删除" json:"deleted"`                                  // 是否删除
}

// TableName OrderGood's table name
func (*OrderGoods) TableName() string {
	return TableNameOrderGoods
}
