// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAddressInfo = "user_address_info"

// UserAddressInfo 收货地址
type UserAddressInfo struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                       // 主键ID
	UserID        int64     `gorm:"column:user_id;not null;comment:用户ID" json:"userId"`                                   // 用户ID
	Province      string    `gorm:"column:province;not null;comment:省" json:"province"`                                   // 省
	City          string    `gorm:"column:city;not null;comment:市" json:"city"`                                           // 市
	Region        string    `gorm:"column:region;not null;comment:区" json:"region"`                                       // 区
	Longitude     int64     `gorm:"column:longitude;not null;comment:经度" json:"longitude"`                                // 经度
	Latitude      int64     `gorm:"column:latitude;not null;comment:纬度" json:"latitude"`                                  // 纬度
	UserName      string    `gorm:"column:user_name;not null;comment:收获人姓名" json:"userName"`                              // 收获人姓名
	PhoneNumber   string    `gorm:"column:phone_number;not null;comment:收获人电话" json:"phoneNumber"`                        // 收获人电话
	AddressDetail string    `gorm:"column:address_detail;not null;comment:详细地址" json:"addressDetail"`                     // 详细地址
	DefaultState  int32     `gorm:"column:default_state;not null;comment:是否默认地址" json:"defaultState"`                     // 是否默认地址
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	Deleted       int32     `gorm:"column:deleted;not null;comment:是否删除" json:"deleted"`                                  // 是否删除
}

// TableName UserAddressInfo's table name
func (*UserAddressInfo) TableName() string {
	return TableNameUserAddressInfo
}
