definitions:
  model.Bar:
    properties:
      createTime:
        description: 创建时间
        type: string
      deleted:
        description: 是否删除
        type: boolean
      id:
        description: 主键ID
        type: integer
      updateTime:
        description: 更新时间
        type: string
      value:
        description: bar value
        type: string
    type: object
  model.Index:
    properties:
      createTime:
        description: 创建时间
        type: string
      defaultConfig:
        description: 指标简介
        type: string
      deleted:
        description: 是否删除
        type: boolean
      desc:
        description: 指标简介
        type: string
      icon:
        description: 指标图标
        type: string
      id:
        description: 主键ID
        type: integer
      name:
        description: 指标名称
        type: string
      updateTime:
        description: 更新时间
        type: string
      warningConfigArray:
        description: 预警配置
        type: string
    type: object
  model.Strategy:
    properties:
      createTime:
        description: 创建时间
        type: string
      deleted:
        description: 是否删除
        type: boolean
      id:
        description: 主键ID
        type: integer
      instId:
        description: 币种ID
        type: string
      strategyName:
        description: 策略名称
        type: string
      subscriptionState:
        description: '订阅状态: 0 未订阅 1 已订阅'
        type: integer
      updateTime:
        description: 更新时间
        type: string
      userId:
        description: 用户ID
        type: integer
    type: object
  v1.CreateStrategyRequest:
    properties:
      InstId:
        type: string
      indexList:
        items:
          $ref: '#/definitions/v1.IndexRequest'
        type: array
      name:
        type: string
      subscriptionState:
        type: integer
      userId:
        type: integer
    required:
    - InstId
    - indexList
    - name
    type: object
  v1.GetProfileResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/v1.GetProfileResponseData'
      message:
        type: string
    type: object
  v1.GetProfileResponseData:
    properties:
      nickname:
        example: alan
        type: string
      userId:
        type: string
    type: object
  v1.IndexRequest:
    properties:
      InstId:
        type: string
      bar:
        type: string
      indexConfig:
        type: string
      indexId:
        type: integer
      warningConfig:
        type: string
    required:
    - InstId
    - bar
    - indexConfig
    - indexId
    - warningConfig
    type: object
  v1.SendSMSCodeRequest:
    properties:
      code:
        example: "123456"
        type: string
      phoneNumber:
        example: "1234567890"
        type: string
    required:
    - code
    - phoneNumber
    type: object
  v1.StrategyIndexRequest:
    properties:
      strategyIndexId:
        type: integer
      userId:
        type: integer
    required:
    - strategyIndexId
    type: object
  v1.StrategyRequest:
    properties:
      strategyId:
        type: integer
      userId:
        type: integer
    required:
    - strategyId
    type: object
  v1.UpdateUserInfoRequest:
    properties:
      phoneNumber:
        type: string
      wallet:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Nunu Example API
  version: 1.0.0
paths:
  /coin/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Bar'
      security:
      - Bearer: []
      summary: 币币信息
      tags:
      - 公共
  /index/bar/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Bar'
      security:
      - Bearer: []
      summary: 时间线
      tags:
      - 公共
  /index/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Index'
      security:
      - Bearer: []
      summary: 指标列表
      tags:
      - 指标
  /index/test:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.IndexRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Index'
      security:
      - Bearer: []
      summary: 指标回测
      tags:
      - 指标
  /sms/code:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.SendSMSCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 发送短信验证码
      tags:
      - 短信
  /strategy/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.CreateStrategyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 创建策略
      tags:
      - 策略
  /strategy/delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.StrategyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 删除策略
      tags:
      - 策略
  /strategy/index/delete:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.StrategyIndexRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 删除策略关联指标
      tags:
      - 策略
  /strategy/index/list:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.StrategyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 获取策略关联指标
      tags:
      - 策略
  /strategy/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Strategy'
      security:
      - Bearer: []
      summary: 获取当前用户的策略列表
      tags:
      - 策略
  /strategy/subscription:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.StrategyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 更新策略订阅状态
      tags:
      - 策略
  /subscription/pay/wallet:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Bearer: []
      summary: 获取订阅支付钱包地址
      tags:
      - 公共
  /subscription/price:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Bar'
      security:
      - Bearer: []
      summary: 获取订阅价格
      tags:
      - 公共
  /transaction/recharge/confirm:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 充值确认
      tags:
      - 交易
  /update/user:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateUserInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 更新用户信息
      tags:
      - 用户模块
  /user:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetProfileResponse'
      security:
      - Bearer: []
      summary: 获取用户信息
      tags:
      - 用户模块
  /verification/sms/code:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.SendSMSCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: 核对验证码
      tags:
      - 短信
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
