name: Deploy with docker

on:
  push:
    # 分支
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: fengqixian1996/hookfunc
          tags: latest
          registry: docker.io
          dockerfile: ./deploy/build/Dockerfile
          buildArgs: APP_CONF=config/prod.yml,APP_RELATIVE_PATH=./cmd/server/...
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}
        
      - uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        name: ssh scp ssh pipelines
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          first_ssh: |-
            echo $WELCOME   
            mkdir -p /home/github/test/test1 &&    
            mkdir -p /home/github/test/test2 &&
          scp: |-
            './test/*' => /home/github/test/
          last_ssh: |-
            echo $LASTSSH &&
            (mkdir test1/test || true)
            ls -la  
