name: Deploy with docker

on:
  push:
    # 分支
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: fengqixian1996/hookfunc
          tags: latest
          registry: docker.io
          dockerfile: ./deploy/build/Dockerfile
          buildArgs: APP_CONF=config/prod.yml,APP_RELATIVE_PATH=./cmd/server/...
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}
        
