name: Deploy with docker

on:
  push:
    # 分支
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: repo/image
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile
          directory: ./hookfuncMedia/deploy/build/
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}
        
